const normalize = require('..')

describe('normalize', () => {
  it('should normalize addresses', () => {
    const fixtures = [
      ['BOULEVARD DU MARECHAL JEAN MARIE DE LATTRE DE TASSIGNY', 'BD MAL J M DE LATTRE DE TASSIGNY'],
      ['SENTIER DE LA CÔTE', 'SENTIER DE LA COTE'],
      ['SQUARE DES SOEURS DE SAINT VINCENT DE PAUL', 'SQ SOEURS DE ST VINCENT DE PAUL'],
      ['RUE LINO BORRINI DIT LINO VENTURA', 'RUE L BORRINI DIT LINO VENTURA'],
      ['RUE ETIENNE GEOFFROY DE SAINT HILAIRE', 'RUE E GEOFFROY DE SAINT HILAIRE'],
      ['RUE DU PRINCE FERDINAND DE BOURBON DES DEUX SICILES', 'RUE P F DE BOURBON DEUX SICILES'],
      ['RUE DU MARECHAL PHILIPPE DE HAUTECLOCQUE DIT LECLERC', 'RUE MAL P DE H DIT LECLERC'],
      ['RUE DU LIEUTENANT DE VAISSEAU JEAN DOMINIQUE ANDRIEUX', 'RUE DU LTDV J DOMINIQUE ANDRIEUX'],
      ['RUE DU GROUPE SCOLAIRE LOUIS BRETON', 'RUE DU GROU SCOLAIRE L BRETON'],
      ['RUE DU CORPS EXPEDITIONNAIRE FRANCAIS EN ITALIE 1943 1944', 'RUE C E FR ITALIE 1943 1944'],
      ['RUE DES FRERES MARC ET JEAN MARIE GAMON', 'RUE DES FRERES M ET J M GAMON'],
      ['TRAVERSE NOTRE DAME DE BON SECOURS', 'TRAVERSE ND DE BON SECOURS'],
      ['AVENUE GEORGES ET CLAUDE CAUSTIER', 'AV GEORGES ET CLAUDE CAUSTIER'],
      ['AVENUE DE LA DIVISION DU GENERAL LECLERC', 'AV DE LA DIVISION DU GAL LECLERC'],
      ['ALLÉE DE L\'ABBAYE NOTRE DAME DU GRAND MARCHÉ', 'ALL DE L ABBAYE ND DU GD MARCHE'],
      ['ALLEE 1ER BATAILLON DU RGT DE BIGORRE FFI 1944 1945', 'ALL 1ER BTN R B FFI 1944 1945'],
      ['AGGLOMERATION DE VILLENEUVE D ENTRAUNES', 'AGGL DE VILLENEUVE D ENTRAUNES'],
      ['SENTIER DE LA RAVINE DES PONCEAUX', 'SENT DE LA RAVINE DES PONCEAUX'],
      ['SENTIER DE LA FONTAINE DU PETIT DAMIETTE', 'SENT DE LA FONT DU PT DAMIETTE'],
      ['RUE EMMANUEL D ASTIER DE LA VIGERIE', 'RUE E D ASTIER DE LA VIGERIE'],
      ['PLACE CHARLES DE GAULLE ET DE LA RESISTANCE', 'PL C DE GAULLE DE LA RESISTANCE'],
      ['ALLEE DES VILLAS DE LA GRANDE BASTIDE', 'ALL DES VILLAS DE LA GDE BASTIDE'],
      ['RUE L APPEL DU 18 JUIN DU GENERAL DE GAULLE', 'RUE APPEL 18 JUIN GAL DE GAULLE'],
      ['ANCIEN CHEMIN DE GRANGE DE PUZAIS AU SCEY', 'ANC CHEM GRANGE PUZAIS AU SCEY'],
      ['BOURG DE SAINT MICHEL L ECLUSE ET LEPARON', 'BOUR ST MICHEL L ECLU ET LEPARON'],
      ['CARREFOUR DU GENERAL JACQUES PARIS DE BOLLARDIERE', 'CARR GAL J PARIS DE BOLLARDIERE'],
      ['CHEMIN DE L EGLISE DE SAINT CHRISTOPHE', 'CHEM DE L EGLI DE ST CHRISTOPHE'],
      ['CARREFOUR JEAN DE LATTRE DE TASSIGNY', 'CARR JEAN DE LATTRE DE TASSIGNY'],
      ['CHEMIN DE LA FERME DES BOIS AU CHEMIN DES MOULINS', 'CHEM FERM BOIS CHEM DES MOULINS'],
      ['CHEMIN DE LA GRANDE RUE AU CHEMIN DES ROBERDES', 'CHEM GDE RUE CHEM DES ROBERDES'],
      ['CHEMIN DE TRAVERSE DE LA FORET DE SENART', 'CHEM DE TRAV DE LA FOR DE SENART'],
      ['CHEMIN DE VILLENEUVE SAINT GEORGES A LA GRANGE', 'CHEM DE V ST GEORGES GRANGE'],
      ['CHEMIN DEPARTEMENTAL 116 D ARPAJON A AUNEAU', 'CHEM DEP 116 D ARPAJON A AUNEAU'],
      ['CHEMIN DES DROITS DE L HOMME ET DE L ENFANT', 'CHEM DROITS HOMME ET DE L ENFANT'],
      ['CENTRE ADMINISTRATIF WALDECK L HUILIER', 'CTRE A WALDECK L HUILIER'],
      ['BOULEVARD SAINT JEAN BAPTISTE DE LA SALLE', 'BD ST JEAN BAPTISTE DE LA SALLE'],
      ['BOURG DE SAINT ETIENNE DES LANDES', 'BOURG DE ST ETIENNE DES LANDES'],
      ['BOURG SAINT JULIEN DES EGLANTIERS', 'BOURG ST JULIEN DES EGLANTIERS'],
      ['CARREFOUR DE L EUROPE PRIX NOBEL DE LA PAIX 2012', 'CARR EUROPE PRIX NOBEL PAIX 2012'],
      ['MONTEE DE L EGLISE SAINT PIERRE SAINT PAUL', 'MONT DE L EGLI ST PIERRE ST PAUL'],
      ['VOIE DE LA DECLARATION UNIVERSELLE DES DROITS DE L HOMME', 'VOIE D UNIVERSELLE DROITS HOMME'],
      ['RUE ALICE DOMON ET LÉONIE DUQUET, SŒUR ALICIA ET SŒUR LÉONIE', 'RUE A D L D S A SOEUR LEONIE']
    ]

    for (const [source, expected] of fixtures) {
      expect(
        normalize(source)
      ).toBe(expected)
    }
  })
})
